# Prometheus Configuration for DigitalTide Monitoring
#
# For cross-platform compatibility:
# - Linux: Use 172.17.0.1 (default Docker bridge IP)
# - Mac/Windows: Use host.docker.internal
# - Or set PROMETHEUS_TARGET_HOST environment variable

global:
  scrape_interval: 15s # How often to scrape targets
  evaluation_interval: 15s # How often to evaluate rules

# Alertmanager configuration (optional, can be added later)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets: ['alertmanager:9093']

# Load rules once and periodically evaluate them
rule_files:
  - 'alerts.yml'

# Scrape configurations
scrape_configs:
  # Monitor Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Monitor DigitalTide API
  # For Linux users: Use prometheus.linux.yml which has 172.17.0.1 instead
  - job_name: 'digitaltide-api'
    static_configs:
      - targets: ['host.docker.internal:3000'] # Mac/Windows Docker Desktop
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Monitor PostgreSQL (using postgres_exporter if added later)
  # - job_name: 'postgres'
  #   static_configs:
  #     - targets: ['postgres-exporter:9187']

  # Monitor Redis (using redis_exporter if added later)
  # - job_name: 'redis'
  #   static_configs:
  #     - targets: ['redis-exporter:9121']

  # Monitor Node.js process metrics
  - job_name: 'node-app'
    static_configs:
      - targets: ['host.docker.internal:3000'] # Cross-platform (use 172.17.0.1 on Linux)
    metrics_path: '/metrics'
